version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
  frontend:
    build: ./frontend
    expose:
      - 3000
    environment:
      - PORT=3000
    depends_on:
      - backend
  backend:
    build: ./backend
    privileged: true
    pid: host
    restart: always
    expose:
      - 8080
    volumes:
      - /proc:/host_proc
    depends_on:
      - db
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: Proyecto1
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: