apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: so1-proyecto2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: alvarog1318/s1p2_consumer:v2.0
        resources:
          limits:
            cpu: "0.5"
            memory: "500Mi"