apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: so1-proyecto2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: grcp-client
        image: alvarog1318/s1p2_consumer:v0.1
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "500m"
            memory: "500Mi"