apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: so1-proyecto2-ingress
  namespace: so1-proyecto2
spec:
  ingressClassName: nginx
  rules:
    - host: 35.226.195.26.nip.io
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: grcp-client-service
                port:
                  number: 3000
            path: /grcp
          - pathType: Prefix
            backend:
              service:
                name: wasm-producer-service
                port:
                  number: 3000
            path: /wasm

# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: so1-proyecto2-ingress
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /data
#   namespace: so1-proyecto2
# spec:
#   ingressClassName: nginx
#   rules:
#   - host: 35.226.195.26.nip.io
#     http:
#       paths:
#       - path: /grcp
#         pathType: Prefix
#         backend:
#           service:
#             name: grcp-client-service
#             port:
#               number: 3000
#       - path: /wasm
#         pathType: Prefix
#         backend:
#           service:
#             name: wasm-producer-service
#             port:
#               number: 80
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: grpc-http-gateway-external
#   namespace: ingress-nginx 
# spec:
#   type: ExternalName
#   externalName: grcp-client-service.so1-proyecto2-svc.cluster.local