// Generated by https://quicktype.io

export interface History {
  cpu: CPUHistory[];
  ram: RAMHistory[];
}

export interface CPUHistory {
  date:       string;
  percentage: string;
}

export interface RAMHistory {
  date:    string;
  percent: string;
}
