// Generated by https://quicktype.io

export interface Processes {
  processes: Process[];
}

export interface Process {
  pid:      number;
  name:     string;
  user:     number;
  children: Child[];
}

export interface Child {
  pid:       number;
  name:      string;
  pidFather: number;
}
