// Generated by https://quicktype.io

export interface RealTime {
  cpu: CPU;
  ram: RAM;
}

export interface CPU {
  percentage: string;
}

export interface RAM {
  totalRam: string;
  freeRam:  string;
  usedRam:  string;
  percent:  string;
  date:     string;
}
