apiVersion: v1
kind: Service
metadata:
  name: wasm-producer-service
  namespace: so1-proyecto2
spec:
  selector:
    app: wasm-producer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP